Upgrade deps and adjust dockerfile/readme
xivapi/nodestone pull request #12
Opened 2024-03-30 00:41 UTC by kalilistic

I didn't touch the tsconfig (yet) but there's probably an opportunity to retarget if ever refactoring the code base. arc convinced me to keep yarn.

2024-03-30 03:19 UTC, kalilistic commented
I'm getting some errors on my server so setting to draft to be safe. It's probably unrelated but I want to make sure.

2024-03-30 10:16 UTC, Supamiu approved these changes
LGTM, what are your server errors tho? Might be worth checking

2024-03-30 13:11 UTC, kalilistic commented
I'll look more later today but here's the error.
`2024-03-30T12:59:40.090548726+00:00 stderr F Corepack is about to download https://repo.yarnpkg.com/4.1.1/packages/yarnpkg-cli/bin/yarn.js.
2024-03-30T12:59:46.814701810+00:00 stdout F ^[[31m^[[1mUsage Error^[[22m^[[39m: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
2024-03-30T12:59:46.814701810+00:00 stdout F
2024-03-30T12:59:46.814701810+00:00 stdout F ^[[1m$ ^[[22myarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...`

2024-03-30 14:40 UTC, kalilistic commented
I rolled back to yarn v1 and it's working fine with alpine now too. The other bug was my own ci - I forgot gha checkout doesn't pull submodules by default.

2024-04-06 23:25 UTC, kalilistic commented
I could be mistaken - but I think pagination was broken where the page number param was not being handled correctly. I was able to replicate this on the current master branch too. Just needed to swap from a `?` to a `&`.

2024-04-07 06:14 UTC, Supamiu approved these changes

2024-04-07 06:17 UTC, Supamiu requested changes

2024-04-07 06:17 UTC, Supamiu commented on src/core/paginated-page-parser.ts
> +            query = `&page=${req.query?.page}`;
I think using URL would be better if we want to fix that, because this will only work if there's already a param in the query, while the previous approach only worked if there was none.

Using URL would make it check beforehand and apply the right separator: https://stackoverflow.com/questions/486896/adding-a-parameter-to-the-url-with-javascript

2024-04-08 07:09 UTC, Supamiu approved these changes

2024-04-08 16:59 UTC, kalilistic commented
Thanks Miu - anything else you need from me on this to merge? I saw you approved but held off the merge so wanted to make sure.

2024-04-08 18:44 UTC, Supamiu commented
Wanted to be sure this was all ready on your end so looks like we are 👍

2024-04-08 18:44 UTC, merged